server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: emr
  main:
    allow-circular-references: true
  profiles:
    include: doc,datasource,emr
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    redis:
      host: 192.168.110.72 # Redis服务器地址
      database: 2 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: kzkj@_Cloud.1
      timeout: 30000ms # 连接超时时间（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 2      # 连接池中的最大空闲连接
          min-idle: 1       # 连接池中的最小空闲连接


knife4j:
  enable: true 
  setting:
    language: zh_cn

logging:
  level:
    com.hit.**: debug
    com.hit.gateway.aop.HttpRequestControllerAspect: trace

